#!/bin/env bash

case $1 in
	latin)
		fcitx5-remote -g latin
		;;
	us)
		fcitx5-remote -g us
		;;
	russian)
		fcitx5-remote -g russian
		;;
	greek)
		fcitx5-remote -g greek
		;;
	chinese)
		fcitx5-remote -g chinese
		;;
	korean)
		notify-send --urgency=critical "Korean is not implemented"
		exit 1
		;;
	*)
		echo Error: unknown layout
		exit 1
		;;
esac

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
